name: Scan Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Extract Docker Images from Helm Chart
      id: extract-images
      run: |
        echo "Running helm template"
        helm template ./helm-chart-directory \
          | grep "image:" \
          | awk '{print $2}' \
          | sort -u > images.txt

        echo "Extracted Docker images:"
        cat images.txt
        if [ ! -s images.txt ]; then
          echo "Error: No images found!" && exit 1
        fi

    - name: Install Trivy
      run: |
        curl -sSfL https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb -o trivy.deb
        sudo dpkg -i trivy.deb

    - name: Run Trivy Scan
      id: trivy-scan
      run: |
        mkdir -p trivy-reports
        while read image; do
          echo "Scanning $image"
          trivy image --format json --output trivy-reports/$(echo $image | sed 's|/|_|g').json $image || echo "Failed to scan $image"
        done < images.txt

    - name: List Generated Reports
      run: |
        echo "Listing reports in trivy-reports/"
        ls -l trivy-reports/

    - name: Upload Trivy Reports
      uses: actions/upload-artifact@v3
      with:
        name: trivy-reports
        path: trivy-reports/
