name: Scan Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan-images:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Helm
    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    # Extract Docker image names from the Helm chart
    - name: Extract Docker Images from Helm Chart
      id: extract-images
      run: |
        helm template ./helm-chart-directory \
          | grep "image:" \
          | awk '{print $2}' \
          | sort -u > images.txt

    # Display the extracted images
    - name: Display extracted images
      run: |
        echo "Extracted Docker Images:"
        cat images.txt

    # Run Trivy scan on each image
    - name: Run Trivy Scan
      id: trivy-scan
      run: |
        mkdir -p trivy-reports
        while read image; do
          echo "Scanning $image"
          trivy image --format json --output trivy-reports/$(echo $image | sed 's|/|_|g').json $image
        done < images.txt

    # Upload Trivy reports as artifacts
    - name: Upload Trivy Reports
      uses: actions/upload-artifact@v3
      with:
        name: trivy-reports
        path: trivy-reports/
